### ISSUE TITLE
What's Next?

### ISSUE THREAD

**Issue by FA-Bubba** [nodeful/Faceply.io#3] opened 2018-03-31 15:10 UTC
The last time I had a dialog with Roman (Oct 2017), he indicated that the project was dormant...

With the recent Facebook issues, and global recommendations to cease using FB Messenger, having an AutoResponder would be an essential way to let others know to contact you another way.

Perhaps Roman can be persuaded to resurrect this project?

**Comment by nodeful** [comment] 2018-04-03 07:19
I don't really use the application myself. I only needed it for a brief moment in my life. I can't invest any of my personal time into this, sorry. Though I'm happy to merge a pull request if someone is willing to fix it. 

Roman

**Comment by nodeful** [comment] 2018-04-03 07:20
and also duplicate of #2 Closing

**Closed as completed by nodeful** 2018-04-03 07:20 UTC
Labels: bug, help wanted

**Comment by nodeful** [comment] 2018-04-03 07:21
and #1
